(env
 (dev
  (flags
   (:standard -w -A))))

(library
 (name test_utils)
 (libraries lib typecheck)
 (modules test_utils))

(executable
 (name test_app_assert)
 (libraries zarith lib typecheck)
 (modules test_app_assert))

(executable
 (name test_layered_assert)
 (libraries zarith lib typecheck)
 (modules test_layered_assert))

(executable
 (name test_double_assert)
 (libraries zarith lib typecheck)
 (modules test_double_assert))

(executable
 (name test_simple)
 (libraries zarith lib typecheck)
 (modules test_simple))
