(env
 (dev
  (flags
   (:standard -w -A))))

(library
 (name test_utils)
 (libraries lib typecheck)
 (modules test_utils))

(executable
 (name test_assert_app)
 (libraries zarith lib typecheck)
 (modules test_assert_app))

(executable
 (name test_shadowing)
 (libraries zarith lib typecheck)
 (modules test_shadowing))

(executable
 (name test_nested_assert)
 (libraries zarith lib typecheck)
 (modules test_nested_assert))

(executable
 (name test_double_assert)
 (libraries zarith lib typecheck)
 (modules test_double_assert))

(executable
 (name test_simple)
 (libraries zarith lib typecheck)
 (modules test_simple))

(executable
 (name test_leq_delay)
 (libraries zarith lib typecheck)
 (modules test_leq_delay))

(executable
 (name test_input_delay)
 (libraries zarith lib typecheck)
 (modules test_input_delay))

(executable
 (name test_output_delay)
 (libraries zarith lib typecheck)
 (modules test_output_delay))
